spring:
  application:
    name: booking-service
server:
  port: 8094

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
