spring:
  application:
    name: passenger-details-service
  jpa:
    show-sql: true

server:
  port: 8092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
