spring:
  application:
    name: parking-service

  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:8888


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8090
