spring:
  application:
    name: passenger-service


  #spring.cloud.config.import-check.enabled=false
#  cloud:
#    config:
#      enabled: false

server:
  port: 8089
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

