
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file://home/diallocodeur/Desktop/SarayaTech/Microservice/airport-management/config-files
  application:
    name: config-server





