
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/diallocodes/config-files
          clone-on-start: true
          search-paths: development
          default-label: master


  application:
    name: config-server

server:
  port: 8888


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka






