
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/diallocodes/config-files.git
          clone-on-start: true

  application:
    name: config-server

server:
  port: 8888






